name: Development

on:
  push:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Lint Source Files
        run: npm run lint
  compile:
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Compile Source Files
        run: npm run compile
