name: Dev

on:
  push:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Lint Source Files
        run: npm run lint
  compile:
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Compile Source Files
        run: npm run compile
  publish:
    runs-on: ubuntu-latest
    needs: [lint, compile]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: next
          check-version: true
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
